name: Check clean build of test cases

on:
  push:
    paths:
      - 'test/**'
      
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build test cases
        run: make -C test
